### ISSUE TITLE
Picture Size probably too big

### ISSUE THREAD

**Issue by mspark** [mspark/MultiModuleCatBot#4]
Sometimes we got an discord API error when sending images. The reason could be too big files. Maybe compression is the way to go

**Comment by mspark** [comment]
```
Jan 22 17:25:22 DIBDEB01FRA4 npm[6902]: /home/catbot/MultiModuleCatBot/node_modules/discord.js/src/rest/RequestHandler.js:154
Jan 22 17:25:22 DIBDEB01FRA4 npm[6902]:       throw new DiscordAPIError(request.path, data, request.method, res.status);
Jan 22 17:25:22 DIBDEB01FRA4 npm[6902]:             ^
Jan 22 17:25:22 DIBDEB01FRA4 npm[6902]: DiscordAPIError: Request entity too large
Jan 22 17:25:22 DIBDEB01FRA4 npm[6902]:     at RequestHandler.execute (/home/catbot/MultiModuleCatBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
Jan 22 17:25:22 DIBDEB01FRA4 npm[6902]:     at processTicksAndRejections (node:internal/process/task_queues:94:5)
Jan 22 17:25:22 DIBDEB01FRA4 npm[6902]:     at async RequestHandler.push (/home/catbot/MultiModuleCatBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
Jan 22 17:25:22 DIBDEB01FRA4 npm[6902]:   method: 'post',
Jan 22 17:25:22 DIBDEB01FRA4 npm[6902]:   path: '/channels/769640571304149022/messages',
Jan 22 17:25:22 DIBDEB01FRA4 npm[6902]:   code: 40005,
Jan 22 17:25:22 DIBDEB01FRA4 npm[6902]:   httpStatus: 413
Jan 22 17:25:22 DIBDEB01FRA4 npm[6902]: }
```
